# set-option -sa terminal-overrides ",xterm*:Tc"
set-option -sa terminal-features ',XXX:RGB'

# Enable mouse support inside of tmux
set -g mouse off

# Set base index to 1 for easier navigation
set -g base-index 1
set -g pane-base-index 1
set-window-option -g renumber-windows on

# Display the tmux bar at the top of the screen
set-option -g status-position top

# Set prefix to be Ctrl-Space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'dracula/tmux'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'jimeh/tmuxifier'
set -g @plugin 'wfxr/tmux-fzf-url'

# Display the battery charge level in the tmux bar
set -g @dracula-battery-label "Bat"

# set vi-mode
set-window-option -g mode-keys vi
set -g @dracula-show-left-icon session

# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind-key -r g display-popup -w 40% -h 40% -E '~/scripts/gbranch'
bind-key -r j display-popup -w 40% -h 40% -E '~/scripts/change'

# sesh config
bind-key "T" run-shell "sesh connect \"$(
	sesh list | fzf-tmux -p 55%,60% \
		--no-sort --border-label ' sesh ' --prompt '⚡  ' \
		--header '  ^a all ^t tmux ^x zoxide ^d tmux kill ^f find' \
		--bind 'tab:down,btab:up' \
		--bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list)' \
		--bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t)' \
		--bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z)' \
		--bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
		--bind 'ctrl-d:execute(tmux kill-session -t {})+change-prompt(⚡  )+reload(sesh list)'
)\""

# split in cwd
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# This line should always be the last one
run '~/.config/tmux/plugins/tpm/tpm'
