[default_session]
startup_command = "~/.config/sesh/startup"

[[session]]
name="tmux config"
path="~/.config/tmux"
startup_command="nvim"

[[session]]
name="nvim config"
path="~/.config/nvim"

[[session]]
name="home"
path="~/"
startup_command="ff"
