[default_session]
startup_command = "aa"

[[session]]
name="tmux config"
path="~/dotfiles/.config/tmux"
startup_command="aa tmux.conf"

[[session]]
name="sesh config"
path="~/dotfiles/.config/sesh"
startup_command="aa sesh.toml"

[[session]]
name="neovim config"
path="~/dotfiles/.config/aa"
startup_command="aa -c ':Telescope find_files'"

[[session]]
name="home"
path="~"
startup_command="ff"

[[session]]
name="BCABackend"
startup_command="tmuxinator start tbca"

[[session]]
name="BCAFrontend"
startup_command="tmuxinator start fba"
