#! /bin/bash
# Author: Andres Court
# Date: 2023-11-10
# Description: Load a tmux session from tmuxifier

sessions=`tmuxifier ls | fzf --reverse`

if [[ -z $sessions ]]; then
     echo "No session selected"
     exit 1
else
     tmuxifier s $sessions
fi
